export default defineEventHandler(() => {
  const webData = [
    {
      id: 1,
      title: "首頁",
      enTitle: "Home Page",
      description:
        "在上一版本中，因新開發了 Line Bot，直接使用 Line 官方帳號就可以發送您的需求到服務提供者手上，為增加 Line 官方會員數以配合 Line Bot 的使用，將加入 Line 會員的連結和使用方式及流程，直接呈現在一進入的頁面中。",
      enDescription:
        "In the previous version, a new Line Bot was developed, allowing users to directly send their requests to service providers using Line's official account. To increase the number of Line official members and accommodate the use of the Line Bot, a link to join Line membership along with its usage instructions and process will be added and displayed on the landing page.",
      painPoints: [
        "搜尋服務在子選單裡，人員搜尋不易。",
        "廣告及廠商沒更多位置曝光。",
        "新服務在子選單裡，用戶較不會點擊進入。",
      ],
      enPainPoints: [
        "The search service is located in the submenu, making it difficult to find the personnel search function.",
        "There are no additional positions for advertising and vendor exposure.",
        "The new service is located in the submenu, resulting in fewer user clicks to access it.",
      ],
      solves: [
        "進入頁面加入給知道需求的用戶快速搜尋。",
        "下方新增廣告連結版位。",
        "重新修改過服務版面，更直覺選擇需求進入內頁。",
      ],
      enSolves: [
        "To cater to users who already know their requirements, consider adding a quick search feature on the entry page.",
        "Add advertising link spaces below.",
        "Revised the service layout for a more intuitive selection of requirements to enter the inner page.",
      ],
      imgs: ["index-1.jpg", "index-2.jpg"],
      alts: ["舊版首頁", "新版首頁"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 2,
      title: "嚴選月嫂頁",
      enTitle: "Carefully Selected Maternity Nanny Page",
      description:
        "過往頁面中，公司列出全部上架的月嫂，無法篩選，頂多就是使用排序方式讓客戶瀏覽，用戶需個別點擊進入月嫂內頁查看。",
      enDescription:
        "In the previous pages, the company listed all the available maternity nannies without the option to filter. At most, they provided sorting options for customers to browse. Users had to individually click on each nanny's page to view their details.",
      painPoints: [
        "人員搜尋不易。",
        "價格不明確。",
        "不知月嫂等級。",
        "評價只有愛心數。",
        "愛月嫂推薦標籤被弱化。",
        "沒有更多篩選機制。",
        "手機版分頁不易點選。",
        "年齡會影響該月嫂的點擊率。",
      ],
      enPainPoints: [
        "Personnel search is not user-friendly.",
        "The prices are not clear or specific.",
        "The maternity nanny levels are not known or specified.",
        "There are only heart ratings without detailed reviews.",
        "The iaunty tag has been downplayed or de-emphasized.",
        "There are no additional filtering mechanisms available.",
        "The mobile version's pagination is not user-friendly and challenging to click on.",
        "Age can influence the click-through rate of the maternity nanny.",
      ],
      solves: [
        "將服務分類。",
        "在卡片式月嫂下標示出價格，並標明金牌月嫂的 Icon，將所有月嫂標明等級，會導致頁面過於雜亂。",
        "將愛心數以小數點一位方式量化。",
        "使用浮動式顯示愛月嫂推薦標籤。",
        "讓左側變成用戶篩選項目（包含可服務日期、地區、證照、等級......）。",
        "以無限捲動方式，使用載入更多按鈕向下載入，以取代分頁按鈕。",
        "弱化月嫂年齡。",
      ],
      enSolves: [
        "Service categorization will be implemented.",
        "The prices will be displayed on card-style maternity nanny listings, with an ICON indicating Gold Medal Nannies. All nannies will be marked with their respective levels, avoiding clutter on the page.",
        "The heart ratings will be quantified using one decimal place.",
        "The 'Ai Yue Maternity Care Recommended' tag will be displayed as a floating element.",
        "The left section will be dedicated to user filtering options, including available service dates, regions, certifications, levels, etc.",
        "An Infinite Scroll method will be used, replacing pagination buttons, allowing users to load more content by clicking 'Load More.'",
        "The emphasis on the age of maternity nannies will be reduced.",
      ],
      imgs: ["aunties-1.jpg", "aunties-2.jpg"],
      alts: ["舊版嚴選月嫂", "新版嚴選月嫂"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 3,
      title: "月嫂個人頁",
      enTitle: "Maternity Nanny Individual Page",
      description: "",
      enDescription: "",
      painPoints: [
        "過多帶有主色系的標籤。",
        "有的月嫂工作及菜色照片太少。",
        "不知這位月嫂有提供哪些服務（如保母服務等）。",
        "覺得不錯想預訂時才發現時間無法配和。",
      ],
      enPainPoints: [
        "Too many labels with dominant color schemes.",
        "Some maternity nannies have too few work and food photos.",
        "It's unclear which services this maternity nanny provides (e.g., babysitting services, etc.).",
        "Users find it inconvenient when they like a nanny but realize that the available time doesn't match their needs when attempting to make a reservation.",
      ],
      solves: [
        "將瀏覽的標籤以文字化方式呈現。",
        "將工作及菜色照放置在主頭像區塊，變化為 Slider 方式切換。",
        "在基本資料區塊加入提供的服務。",
        "需求日期依照前面嚴選月嫂頁的篩選方式先行篩選，而桌機版也將月嫂行事曆放置在上方。",
      ],
      enSolves: [
        "Convert the tag labels into text format for better readability.",
        "Place work and food photos in the main profile area and use a slider to switch between them.",
        "Incorporate the list of provided services into the basic information section.",
        "Filter the availability date according to the criteria used in the 'Carefully Selected Maternity Nanny' page, and position the maternity nanny's calendar on top for desktop version.",
      ],
      imgs: ["aunty-1.jpg", "aunty-2.jpg"],
      alts: ["舊版個人頁", "新版個人頁"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 4,
      title: "服務費用頁",
      enTitle: "Service Fees Page",
      description: "",
      enDescription: "",
      painPoints: [
        "客戶嫌麻煩，只是在比價，還必須自己換算一天的價格。",
        "有網頁價格只是最低價，預訂價格往往比呈現的要高。",
        "客戶不想要價格過高的月嫂或是新手月嫂。",
        "面試前不明確月嫂等級及經驗。",
      ],
      enPainPoints: [
        "Customers find it troublesome as they are merely comparing prices and have to manually calculate the daily rate.",
        "Some web page prices display the minimum rate, but the actual booking price is often higher.",
        "Customers prefer not to hire maternity nannies with excessively high prices or those who are inexperienced.",
        "Customers are unclear about the maternity nanny's level and experience before the interview.",
      ],
      solves: [
        "將月嫂分級，並標示這級別月嫂每天最低時數費用，價格將不至於落差太大。",
        "天數部分將於預訂單時做選擇，客戶可依自身需求做調整。",
        "每個等級的月嫂顯示最低的經驗、服務人數及評價值，客戶可參考所需月嫂等級。",
      ],
      enSolves: [
        "Implement a grading system for maternity nannies, and indicate the minimum daily rate for each grade to minimize significant price disparities.",
        "For the number of days required, customers will make selections during the booking process, allowing them to adjust based on their own needs.",
        "For each grade of maternity nanny, display the minimum experience, number of serviced individuals, and rating value, enabling customers to consider their preferred maternity nanny level.",
      ],
      imgs: ["fee-1.jpg", "fee-2.jpg"],
      alts: ["舊版服務費", "新版服務費"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 5,
      title: "課程活動頁",
      enTitle: "Course Page",
      description: "",
      enDescription: "",
      painPoints: [
        "不知道上課地點。",
        "不知名額額滿沒。",
        "不知要上什麼課程。",
      ],
      enPainPoints: [
        "Unclear about the class location.",
        "Not sure if the class has reached full capacity.",
        "Unaware of the available course offerings.",
      ],
      solves: [
        "將課程以卡片式方式呈現。",
        "卡片上標示上課地區及人數，名額快額滿時將標示剩幾位名額。",
        "增加課程地圖清楚知道自己及課程階段，方便學員依自身能力選擇所需課程。",
      ],
      enSolves: [
        "Present the courses in a card-style format.",
        "On the card, indicate the class location and the number of participants. When the remaining slots are limited, show the number of available spots.",
        "Incorporate a course map to provide clear information about the course stages, enabling students to select the appropriate courses based on their abilities.",
      ],
      imgs: ["class-1.jpg", "class-2.jpg"],
      alts: ["舊版課程", "新版課程"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 6,
      title: "部落格頁",
      enTitle: "Blog Page",
      description: "",
      enDescription: "",
      painPoints: [
        "主頁一次性瀏覽文章篇幅太少。",
        "無法快速知道哪些文章主題較熱門。",
        "安插廣告區塊較少。",
        "企業色區塊較多且重，會影響插圖。",
      ],
      enPainPoints: [
        "The homepage displays too few articles at once, requiring frequent scrolling.",
        "Difficult to quickly identify the most popular article topics.",
        "There are fewer advertisement placements.",
        "The excessive use of corporate-themed blocks hinders the visibility and placement of illustrations.",
      ],
      solves: [
        "將文章加入近期新增文章五篇，其中可安插廣告欄位。",
        "右側歸類出瀏覽數較多的熱門文章，其中可安插廣告欄位。",
        "弱化企業色，讓視覺集中在插圖。",
      ],
      enSolves: [
        "Include a section for displaying the five most recent articles, with the option to place advertisement slots.",
        "On the right-hand side, categorize and display the most popular articles based on views, with the option to place advertisement slots.",
        "Reduce the prominence of corporate-themed elements, allowing the visual focus to be on illustrations.",
      ],
      imgs: ["blog-1.jpg", "blog-2.jpg"],
      alts: ["舊版部落格", "新版部落格"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 7,
      title: "常見問題頁",
      enTitle: "FAQ Page",
      description: "所有問題都集中在一起，沒有特別切分出來。",
      enDescription:
        "All questions are consolidated together without specific categorization.",
      painPoints: [
        "展開後會難以辨別目前在哪一主項目。",
        "手機版將會導致頁面過長。",
      ],
      enPainPoints: [
        "After expanding, it becomes difficult to identify the current main topic.",
        "The mobile version will result in an excessively long page.",
      ],
      solves: [
        "將主項目以圖形化區分，能清楚知道目前所在項目分類。",
        "點擊主項目進入才會顯示項目的子問題，解決手機上瀏覽不易。",
        "將相同的題型歸至於同一項目的子問題。",
      ],
      enSolves: [
        "Use graphical elements to visually differentiate main topics, making it clear which category is currently selected.",
        "Clicking on a main topic will display its respective sub-questions, making it more user-friendly for mobile browsing.",
        "Group similar question types under the same sub-questions of a main topic.",
      ],
      imgs: ["QA-1.jpg", "QA-2.jpg"],
      alts: ["舊版常見問題", "新版常見問題"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 8,
      title: "登入頁",
      enTitle: "Login Page",
      description: "",
      enDescription: "",
      painPoints: [
        "因有訪客式登入，導致減少了使用者加入會員意願。",
        "加入的會員很容易忘記自己登入帳密。",
      ],
      enPainPoints: [
        "The guest login option has resulted in a decrease in users' willingness to sign up as members.",
        "Registered members frequently forget their login credentials.",
      ],
      solves: [
        "取消訪客式登入。",
        "建議使用者使用常用的社群帳號快速登入，不用再填寫麻煩的註冊資料。",
      ],
      enSolves: [
        "Disable guest login.",
        "Suggest users to use commonly used social media accounts for quick login, eliminating the need to fill out tedious registration information.",
      ],
      imgs: ["login-1.jpg", "login-2.jpg"],
      alts: ["舊版登入", "新版登入"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 9,
      title: "腳尾頁",
      enTitle: "Footer Page",
      description: "",
      enDescription: "",
      painPoints: [
        "Footer 的聯絡我們表單較少使用者會填寫，且曾受過駭客攻擊。",
        "許多客戶說找不到服務滿意者問卷按鈕。",
      ],
      enPainPoints: [
        "The contact us form in the footer is less frequently used by users, and it has been targeted by hackers in the past.",
        "Many customers have reported difficulty finding the service satisfaction survey button.",
      ],
      solves: [
        "將聯絡我們表單移除，並在選單上還有常見問題裡露出，讓使用者可以輕鬆找到我們。",
        "因色系接近又在最底層，使用者不易發現，固將下方整列選單都併入 Footer 分類選項裡。",
      ],
      enSolves: [
        "Remove the contact us form and display it in the frequently asked questions section on the menu, making it easily accessible for users.",
        "Due to its color similarity and placement at the bottom, users may overlook it. Therefore, integrate the entire row of menu options at the bottom into the Footer category selection.",
      ],
      imgs: ["footer-1.jpg", "footer-2.jpg"],
      alts: ["舊版腳尾頁", "新版腳尾頁"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 10,
      title: "需求表單頁",
      enTitle: "Form Page",
      description: "",
      enDescription: "",
      painPoints: [
        "表單樣式較老舊。",
        "無法指定服務人員，需特別註明。",
        "無法選擇所需要的服務，需來電洽詢，較無彈性。",
      ],
      enPainPoints: [
        "The form style looks outdated.",
        "It is not possible to specify a service provider, and it needs to be explicitly mentioned.",
        "The form lacks the option to select the desired service, requiring users to make inquiries by phone, which reduces flexibility.",
      ],
      solves: [
        "將色系改為較清爽的風格，並加入小互動及插圖。",
        "從服務者個人頁面進入預訂，服務人員將指定為選定的服務提供者。",
        "服務項目改為下拉式選項，服務不同則所填寫的表單格式不同。",
      ],
      enSolves: [
        "Revamp the color scheme to a more refreshing style and incorporate small interactions and illustrations.",
        "From the service provider's individual page, users can enter the booking process, and the selected service provider will be automatically assigned.",
        "Change the service options to a dropdown menu, and the form format will vary based on the selected service.",
      ],
      imgs: ["form-1.jpg", "form-2.jpg"],
      alts: ["舊版需求表單", "新版需求表單"],
      enAlts: ["Old Vision", "New Vision"],
    },
    {
      id: 11,
      title: "服務者資料頁",
      enTitle: "Service Provider Profile Page",
      description: "",
      enDescription: "",
      painPoints: ["線上填寫資料太多。", "不知道現在等級。"],
      enPainPoints: [
        "There is too much information to fill out online.",
        "Unclear about the current level of the service provider.",
      ],
      solves: [
        "將證照資料等拆開填寫。",
        "審核通過後依經驗及能力在上方顯示級別。",
      ],
      enSolves: [
        "Split the information, including certifications, into separate sections for filling out.",
        "After approval, display the service provider's level above based on their experience and capabilities.",
      ],
      imgs: ["worker-1.jpg", "worker-2.jpg"],
      alts: ["舊版服務者資料", "新版服務者資料"],
      enAlts: ["Old Vision", "New Vision"],
    },
  ];

  return { webData };
});
